services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PROTOCOL=https
      - N8N_SSL_KEY=/certs/localhost-key.pem
      - N8N_SSL_CERT=/certs/localhost.pem
    volumes:
      - ./certs:/certs

      