version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: 0.0.0.0:11434

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_AUTH: "False"
    depends_on:
      - ollama
    volumes:
      - openwebui_data:/app/backend/data

  api:
    build: ./services/api
    container_name: forecast-api
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: http://ollama:11434

  ui:
    build: ./services/ui
    container_name: forecast-ui
    ports:
      - "8501:8501"
    depends_on:
      - api

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false   # for local dev only
    depends_on:
      - api
  postgres:
    image: postgres:15
    container_name: forecast-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forecast_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  ollama_data:
  openwebui_data:
      